[package]
name = "visualhash"
version = "0.1.0"
authors = ["Dalek-Sec <Dalek-Sec@users.noreply.github.com>"]
edition = "2018"

[dependencies]
rust-argon2 = "0.4.0"
image = "0.21.1"

[[bin]]
name = "vish"
